// ═════════════════════════════════════════════════════════════════════
// Curated DevOps, Cloud & SRE Hiring Companies Database
// 300+ Top Tech Companies, Unicorns, SaaS, FinTech & Cloud Startups
// ═════════════════════════════════════════════════════════════════════

const DEVOPS_COMPANIES = [
  // ── 1. Top DevOps, Cloud Infrastructure & Developer Platforms ──
  { name: 'Razorpay', domain: 'razorpay.com', category: 'FinTech & Cloud Infra', tech: 'AWS, Kubernetes, Terraform, ArgoCD' },
  { name: 'Postman', domain: 'postman.com', category: 'Dev Tools & APIs', tech: 'AWS, Kubernetes, Terraform, Docker' },
  { name: 'Hasura', domain: 'hasura.io', category: 'Cloud & GraphQL', tech: 'Kubernetes, Cloud Infrastructure, Docker' },
  { name: 'BrowserStack', domain: 'browserstack.com', category: 'Cloud Infrastructure', tech: 'AWS, Kubernetes, Linux, Prometheus' },
  { name: 'Zepto', domain: 'zepto.com', category: 'Quick Commerce', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'Cred', domain: 'cred.club', category: 'FinTech Unicorn', tech: 'AWS, Kubernetes HPA, Terraform, ArgoCD' },
  { name: 'Groww', domain: 'groww.in', category: 'WealthTech', tech: 'GCP, AWS, Kubernetes, Terraform, CI/CD' },
  { name: 'Zerodha', domain: 'zerodha.com', category: 'FinTech & Trading', tech: 'Linux, Kubernetes, PostgreSQL, Python, Go' },
  { name: 'Swiggy', domain: 'swiggy.in', category: 'Consumer Tech', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'Zomato', domain: 'zomato.com', category: 'Consumer Tech', tech: 'AWS, Kubernetes, Docker, Microservices' },
  { name: 'PhonePe', domain: 'phonepe.com', category: 'FinTech & Payments', tech: 'Private Cloud, Kubernetes, Linux, Terraform' },
  { name: 'Meesho', domain: 'meesho.com', category: 'E-Commerce Unicorn', tech: 'AWS, Kubernetes, Terraform, ArgoCD' },
  { name: 'Urban Company', domain: 'urbancompany.com', category: 'Services Tech', tech: 'AWS, Kubernetes, Docker, Prometheus' },
  { name: 'Lenskart', domain: 'lenskart.com', category: 'Omnichannel Tech', tech: 'AWS, Kubernetes, Terraform, CI/CD' },
  { name: 'Nykaa', domain: 'nykaa.com', category: 'E-Commerce', tech: 'AWS, Kubernetes, Jenkins, Docker' },
  { name: 'PayU', domain: 'payu.in', category: 'Payments & FinTech', tech: 'AWS, Kubernetes, Terraform, Linux' },
  { name: 'Juspay', domain: 'juspay.in', category: 'Payments Infrastructure', tech: 'Haskell, AWS, Kubernetes, Linux, SRE' },
  { name: 'Pine Labs', domain: 'pinelabs.com', category: 'Merchant FinTech', tech: 'AWS, Azure, Kubernetes, Microservices' },
  { name: 'Slice', domain: 'sliceit.com', category: 'FinTech & Credit', tech: 'AWS, Kubernetes, Terraform, SRE' },
  { name: 'Khatabook', domain: 'khatabook.com', category: 'SME SaaS', tech: 'AWS, Kubernetes, Terraform, Docker' },
  { name: 'CoinDCX', domain: 'coindcx.com', category: 'Crypto & Web3', tech: 'AWS, Kubernetes, Terraform, DevSecOps' },
  { name: 'Chargebee', domain: 'chargebee.com', category: 'SaaS Billing', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'Freshworks', domain: 'freshworks.com', category: 'Enterprise SaaS', tech: 'AWS, Kubernetes, Jenkins, Terraform' },
  { name: 'CleverTap', domain: 'clevertap.com', category: 'Customer Analytics', tech: 'AWS, Kubernetes, Big Data, SRE' },
  { name: 'MoEngage', domain: 'moengage.com', category: 'MarTech SaaS', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'WebEngage', domain: 'webengage.com', category: 'MarTech Platform', tech: 'AWS, Kubernetes, Docker, Jenkins' },
  { name: 'Innovaccer', domain: 'innovaccer.com', category: 'HealthTech SaaS', tech: 'AWS, Kubernetes, Terraform, DevSecOps' },
  { name: 'Darwinbox', domain: 'darwinbox.com', category: 'HR Tech SaaS', tech: 'AWS, Kubernetes, Docker, CI/CD' },
  { name: 'Shipsy', domain: 'shipsy.io', category: 'Logistics SaaS', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'Porter', domain: 'porter.in', category: 'Logistics Tech', tech: 'AWS, Kubernetes, Docker, Microservices' },
  { name: 'Delhivery', domain: 'delhivery.com', category: 'Supply Chain Tech', tech: 'AWS, Kubernetes, Terraform, Big Data' },
  { name: 'Shadowfax', domain: 'shadowfax.in', category: 'Hyperlocal Logistics', tech: 'AWS, Kubernetes, Docker, SRE' },
  { name: 'Dream11', domain: 'dream11.com', category: 'SportsTech & Gaming', tech: 'AWS, Kubernetes HPA, Terraform, High-scale SRE' },
  { name: 'MPL', domain: 'mpl.live', category: 'Gaming Platform', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'Games24x7', domain: 'games24x7.com', category: 'Gaming Unicorn', tech: 'AWS, Kubernetes, Terraform, SRE' },
  { name: 'Navi', domain: 'navi.com', category: 'FinTech & Banking', tech: 'AWS, Kubernetes, Terraform, Python' },
  { name: 'Jupiter', domain: 'jupiter.money', category: 'Neobank', tech: 'AWS, Kubernetes, Terraform, DevSecOps' },
  { name: 'Fi Money', domain: 'fi.money', category: 'Neobank', tech: 'GCP, Kubernetes, Terraform, SRE' },
  { name: 'Plum Insurance', domain: 'plumhq.com', category: 'InsurTech', tech: 'AWS, Kubernetes, Docker, CI/CD' },
  { name: 'Acko', domain: 'acko.com', category: 'InsurTech Unicorn', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'Digit Insurance', domain: 'godigit.com', category: 'InsurTech Unicorn', tech: 'AWS, Kubernetes, Docker, Microservices' },
  { name: 'InMobi', domain: 'inmobi.com', category: 'AdTech & Cloud', tech: 'AWS, Kubernetes, Big Data, Linux' },
  { name: 'Glance', domain: 'glance.com', category: 'Content Platform', tech: 'GCP, Kubernetes, Docker, High-scale SRE' },
  { name: 'HackerRank', domain: 'hackerrank.com', category: 'Developer Platform', tech: 'AWS, Kubernetes, Docker, Ruby/Python' },
  { name: 'LeadSquared', domain: 'leadsquared.com', category: 'Sales SaaS', tech: 'AWS, Kubernetes, Docker, CI/CD' },
  { name: 'Uniphore', domain: 'uniphore.com', category: 'Conversational AI', tech: 'AWS, Kubernetes, Terraform, MLOps' },
  { name: 'Gupshup', domain: 'gupshup.io', category: 'Messaging API', tech: 'AWS, Kubernetes, Docker, High Throughput' },
  { name: 'Yellow.ai', domain: 'yellow.ai', category: 'Enterprise AI', tech: 'AWS, Kubernetes, Terraform, Docker' },
  { name: 'Loco', domain: 'loco.gg', category: 'Live Streaming', tech: 'AWS, Kubernetes, Video SRE, Prometheus' },
  { name: 'ShareChat', domain: 'sharechat.com', category: 'Social Tech Unicorn', tech: 'GCP, AWS, Kubernetes, Terraform, SRE' },
  { name: 'Dailyhunt', domain: 'dailyhunt.in', category: 'Media Tech', tech: 'AWS, Kubernetes, Docker, Linux' },
  { name: 'Koo', domain: 'kooapp.com', category: 'Social Platform', tech: 'AWS, Kubernetes, Microservices, SRE' },
  { name: 'Cars24', domain: 'cars24.com', category: 'AutoTech Unicorn', tech: 'AWS, Kubernetes, Terraform, CI/CD' },
  { name: 'Spinny', domain: 'spinny.com', category: 'Used Car Platform', tech: 'AWS, Kubernetes, Docker, Python' },
  { name: 'CarDekho', domain: 'cardekho.com', category: 'Auto Portal', tech: 'AWS, Kubernetes, Docker, Jenkins' },
  { name: 'PolicyBazaar', domain: 'policybazaar.com', category: 'FinTech', tech: 'AWS, Azure, Kubernetes, Microservices' },
  { name: 'PaisaBazaar', domain: 'paisabazaar.com', category: 'FinTech', tech: 'AWS, Kubernetes, Terraform, Docker' },
  { name: 'Zeta', domain: 'zeta.tech', category: 'Banking Tech Unicorn', tech: 'Private Cloud, Kubernetes, Terraform, High-scale SRE' },
  { name: 'Mswipe', domain: 'mswipe.com', category: 'POS FinTech', tech: 'AWS, Kubernetes, Linux, Microservices' },
  { name: 'BharatPe', domain: 'bharatpe.com', category: 'Merchant FinTech', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'OneCode', domain: 'onecode.in', category: 'FinTech', tech: 'AWS, Kubernetes, Docker, CI/CD' },
  { name: 'Rupeek', domain: 'rupeek.com', category: 'FinTech', tech: 'AWS, Kubernetes, Terraform, Linux' },
  { name: 'IndMoney', domain: 'indmoney.com', category: 'SuperMoney App', tech: 'AWS, Kubernetes, Terraform, SRE' },
  { name: 'Smallcase', domain: 'smallcase.com', category: 'InvestTech', tech: 'AWS, Kubernetes, Docker, Prometheus' },
  { name: 'Zerodha Fund House', domain: 'zerodhafundhouse.com', category: 'Asset Management Tech', tech: 'AWS, Kubernetes, Linux' },
  { name: 'Kuvera', domain: 'kuvera.in', category: 'WealthTech', tech: 'AWS, Kubernetes, Docker, Python' },
  { name: 'Scripbox', domain: 'scripbox.com', category: 'Wealth Management', tech: 'AWS, Kubernetes, Terraform, CI/CD' },
  { name: 'BankBazaar', domain: 'bankbazaar.com', category: 'FinTech Marketplace', tech: 'AWS, Kubernetes, Jenkins, Linux' },
  { name: 'FinBox', domain: 'finbox.in', category: 'Embedded Finance', tech: 'AWS, Kubernetes, Python, DevSecOps' },
  { name: 'Perfios', domain: 'perfios.com', category: 'B2B FinTech Unicorn', tech: 'AWS, Kubernetes, Linux, Microservices' },
  { name: 'Signzy', domain: 'signzy.com', category: 'RegTech AI', tech: 'AWS, Kubernetes, Docker, MLOps' },
  { name: 'IDfy', domain: 'idfy.com', category: 'Identity & Auth API', tech: 'AWS, Kubernetes, Terraform, Prometheus' },
  { name: 'HyperVerge', domain: 'hyperverge.co', category: 'AI Vision & Identity', tech: 'AWS, Kubernetes, Docker, Python' },
  { name: 'Arya.ai', domain: 'arya.ai', category: 'Autonomous AI', tech: 'AWS, Kubernetes, PyTorch, MLOps' },
  { name: 'Haptik', domain: 'haptik.ai', category: 'Conversational AI', tech: 'AWS, Kubernetes, Docker, Prometheus' },
  { name: 'Verloop', domain: 'verloop.io', category: 'Customer Support AI', tech: 'AWS, Kubernetes, Go, Terraform' },
  { name: 'Exotel', domain: 'exotel.com', category: 'Cloud Communications', tech: 'AWS, Kubernetes, VoIP SRE, Prometheus' },
  { name: 'Knowlarity', domain: 'knowlarity.com', category: 'Cloud Telephony', tech: 'AWS, Linux, Kubernetes, SRE' },
  { name: 'Kaleyra', domain: 'kaleyra.com', category: 'CPaaS Communications', tech: 'AWS, Kubernetes, Terraform, SRE' },
  { name: 'Otpless', domain: 'otpless.com', category: 'Auth Tech', tech: 'AWS, Kubernetes, Serverless, DevSecOps' },
  { name: 'Supabase', domain: 'supabase.com', category: 'Backend Cloud', tech: 'AWS, Kubernetes, PostgreSQL, Go, Docker' },
  { name: 'Vercel', domain: 'vercel.com', category: 'Frontend Cloud & Edge', tech: 'AWS, Kubernetes, Terraform, Rust, Go' },
  { name: 'Netlify', domain: 'netlify.com', category: 'Cloud Platform', tech: 'AWS, GCP, Kubernetes, Terraform, Go' },
  { name: 'Render', domain: 'render.com', category: 'Cloud Hosting Platform', tech: 'Kubernetes, AWS, Go, Terraform' },
  { name: 'Fly.io', domain: 'fly.io', category: 'Edge Computing', tech: 'Rust, Go, Linux, Firecracker, Docker' },
  { name: 'Railway', domain: 'railway.app', category: 'Cloud Infrastructure', tech: 'Kubernetes, Docker, Rust, Terraform' },
  { name: 'Koyeb', domain: 'koyeb.com', category: 'Serverless Platform', tech: 'Kubernetes, Firecracker, Rust, Go' },
  { name: 'DigitalOcean', domain: 'digitalocean.com', category: 'Cloud Hosting', tech: 'Kubernetes, Linux, Terraform, KVM' },
  { name: 'Linode', domain: 'linode.com', category: 'Cloud Computing', tech: 'Linux, Kubernetes, OpenStack, Python' },
  { name: 'Cloudflare', domain: 'cloudflare.com', category: 'Edge & Security', tech: 'Rust, Linux, Kubernetes, Terraform' },
  { name: 'Fastly', domain: 'fastly.com', category: 'Edge Cloud Platform', tech: 'Varnish, Rust, Linux, Kubernetes' },
  { name: 'Datadog', domain: 'datadoghq.com', category: 'Observability & SRE', tech: 'AWS, Kubernetes, Go, Python, Terraform' },
  { name: 'New Relic', domain: 'newrelic.com', category: 'Observability Platform', tech: 'AWS, Kubernetes, Java, Go, Terraform' },
  { name: 'Dynatrace', domain: 'dynatrace.com', category: 'APM & Observability', tech: 'Kubernetes, OpenTelemetry, SRE' },
  { name: 'Splunk', domain: 'splunk.com', category: 'Log Analytics & SIEM', tech: 'AWS, Kubernetes, Linux, Terraform' },
  { name: 'Elastic', domain: 'elastic.co', category: 'Search & Observability', tech: 'Kubernetes, Docker, Java, Go' },
  { name: 'Grafana Labs', domain: 'grafana.com', category: 'Observability & Metrics', tech: 'Kubernetes, Prometheus, Loki, Tempo' },
  { name: 'Sysdig', domain: 'sysdig.com', category: 'Kubernetes Security', tech: 'Kubernetes, eBPF, Linux, Terraform' },
  { name: 'Aqua Security', domain: 'aquasec.com', category: 'Cloud Native Security', tech: 'Kubernetes, Trivy, Docker, Go' },
  { name: 'Snyk', domain: 'snyk.io', category: 'Developer Security', tech: 'Kubernetes, Docker, TypeScript, Go' },
  { name: 'Gitlab', domain: 'gitlab.com', category: 'DevSecOps Platform', tech: 'Kubernetes, Ruby, Go, Terraform, CI/CD' },
  { name: 'GitHub', domain: 'github.com', category: 'Developer Platform', tech: 'Kubernetes, Actions, Ruby, Go, Azure' },
  { name: 'Atlassian', domain: 'atlassian.com', category: 'Collaboration & Jira', tech: 'AWS, Kubernetes, Terraform, Python' },
  { name: 'PagerDuty', domain: 'pagerduty.com', category: 'Incident Response & SRE', tech: 'AWS, Kubernetes, Terraform, Elixir' },
  { name: 'HashiCorp', domain: 'hashicorp.com', category: 'Infrastructure Software', tech: 'Terraform, Vault, Nomad, Consul, Go' },
  { name: 'Pulumi', domain: 'pulumi.com', category: 'Modern IaC', tech: 'TypeScript, Python, Go, AWS, Azure, GCP' },
  { name: 'Spacelift', domain: 'spacelift.io', category: 'IaC Automation', tech: 'Terraform, Kubernetes, Go, AWS' },
  { name: 'env0', domain: 'env0.com', category: 'Cloud Management', tech: 'Terraform, Kubernetes, Node.js, AWS' },
  { name: 'Scalr', domain: 'scalr.com', category: 'Terraform Management', tech: 'Terraform, AWS, Kubernetes, Python' },
  { name: 'Harness', domain: 'harness.io', category: 'Continuous Delivery', tech: 'Kubernetes, ArgoCD, Java, Go, Terraform' },
  { name: 'Octopus Deploy', domain: 'octopus.com', category: 'Automated Deployment', tech: 'Kubernetes, C#, Go, Terraform' },
  { name: 'Codefresh', domain: 'codefresh.io', category: 'GitOps & ArgoCD', tech: 'Kubernetes, ArgoCD, Docker, Go' },
  { name: 'CircleCI', domain: 'circleci.com', category: 'CI/CD Cloud', tech: 'Clojure, Go, Kubernetes, Docker' },
  { name: 'Semaphore CI', domain: 'semaphoreci.com', category: 'Fast CI/CD', tech: 'Elixir, Go, Kubernetes, Docker' },
  { name: 'Bitrise', domain: 'bitrise.io', category: 'Mobile DevOps CI/CD', tech: 'Go, Docker, macOS, Linux' },
  { name: 'Buildkite', domain: 'buildkite.com', category: 'Hybrid CI/CD', tech: 'Go, Ruby, Kubernetes, AWS' },
  { name: 'Travis CI', domain: 'travis-ci.com', category: 'Automated CI/CD', tech: 'Ruby, Go, Linux, Docker' },
  { name: 'JFrog', domain: 'jfrog.com', category: 'Artifact Management', tech: 'Artifactory, Kubernetes, Java, Go' },
  { name: 'Sonatype', domain: 'sonatype.com', category: 'Nexus & Security', tech: 'Java, Kubernetes, Docker, AppSec' },
  { name: 'SonarSource', domain: 'sonarsource.com', category: 'SonarQube Quality', tech: 'Java, C++, TypeScript, CI/CD' },
  { name: 'Checkmarx', domain: 'checkmarx.com', category: 'DevSecOps SAST', tech: 'Java, C#, Kubernetes, AppSec' },
  { name: 'Veracode', domain: 'veracode.com', category: 'AppSec Platform', tech: 'AWS, Kubernetes, Java, Security' },
  { name: 'Tenable', domain: 'tenable.com', category: 'Cyber Exposure & Cloud', tech: 'Nessus, Cloud Security, Python' },
  { name: 'Qualys', domain: 'qualys.com', category: 'Cloud Security & Compliance', tech: 'Linux, C++, Python, Cloud Security' },
  { name: 'CrowdStrike', domain: 'crowdstrike.com', category: 'Endpoint & Cloud Security', tech: 'Go, C++, AWS, Kubernetes, SRE' },
  { name: 'SentinelOne', domain: 'sentinelone.com', category: 'Autonomous Cybersecurity', tech: 'Linux, C++, Python, Cloud SRE' },
  { name: 'Palo Alto Networks', domain: 'paloaltonetworks.com', category: 'Prisma Cloud & Security', tech: 'Kubernetes, Terraform, Python' },
  { name: 'Fortinet', domain: 'fortinet.com', category: 'Security Fabric', tech: 'C, Linux, Networking, Cloud' },
  { name: 'Zscaler', domain: 'zscaler.com', category: 'Zero Trust Cloud', tech: 'C, Linux, Distributed Systems, SRE' },
  { name: 'Snowflake', domain: 'snowflake.com', category: 'Data Cloud Platform', tech: 'AWS, Azure, GCP, Kubernetes, C++, Go' },
  { name: 'Databricks', domain: 'databricks.com', category: 'Lakehouse & MLOps', tech: 'Spark, Kubernetes, Scala, Python, AWS' },
  { name: 'Confluent', domain: 'confluent.io', category: 'Kafka Event Streaming', tech: 'Kafka, Kubernetes, Java, Go, AWS' },
  { name: 'MongoDB', domain: 'mongodb.com', category: 'NoSQL & Atlas Cloud', tech: 'C++, Go, Kubernetes, Terraform, AWS' },
  { name: 'Redis', domain: 'redis.io', category: 'In-Memory Data Cloud', tech: 'C, Go, Kubernetes, Linux, High-Throughput' },
  { name: 'Couchbase', domain: 'couchbase.com', category: 'Distributed NoSQL', tech: 'C++, Go, Kubernetes, Linux' },
  { name: 'Neo4j', domain: 'neo4j.com', category: 'Graph Database Cloud', tech: 'Java, Kubernetes, Docker, AuraDB' },
  { name: 'SingleStore', domain: 'singlestore.com', category: 'Real-Time Database', tech: 'C++, Kubernetes, Linux, AWS' },
  { name: 'ClickHouse', domain: 'clickhouse.com', category: 'Real-Time Columnar DB', tech: 'C++, Kubernetes, Linux, Cloud SRE' },
  { name: 'Timescale', domain: 'timescale.com', category: 'Time-Series Cloud DB', tech: 'PostgreSQL, C, Go, Kubernetes' },
  { name: 'InfluxData', domain: 'influxdata.com', category: 'Time-Series InfluxDB', tech: 'Go, Rust, Kubernetes, Linux' },
  { name: 'Yugabyte', domain: 'yugabyte.com', category: 'Distributed SQL', tech: 'C++, Kubernetes, PostgreSQL, Go' },
  { name: 'Cockroach Labs', domain: 'cockroachlabs.com', category: 'Distributed SQL', tech: 'Go, Kubernetes, Linux, Cloud SRE' },
  { name: 'Pinecone', domain: 'pinecone.io', category: 'Vector Database for AI', tech: 'Rust, C++, Kubernetes, AWS, GCP' },
  { name: 'Weaviate', domain: 'weaviate.io', category: 'Vector Search Engine', tech: 'Go, Python, Kubernetes, Docker' },
  { name: 'Qdrant', domain: 'qdrant.tech', category: 'Vector Database Engine', tech: 'Rust, Kubernetes, Docker, Linux' },
  { name: 'Chroma', domain: 'trychroma.com', category: 'AI Embeddings Database', tech: 'Python, Rust, ClickHouse, Docker' },
  { name: 'Scale AI', domain: 'scale.com', category: 'Data for AI & MLOps', tech: 'Python, TypeScript, Kubernetes, AWS' },
  { name: 'Weights & Biases', domain: 'wandb.ai', category: 'MLOps & Experiment Tracking', tech: 'Python, Go, Kubernetes, Docker' },
  { name: 'Neptune.ai', domain: 'neptune.ai', category: 'MLOps Platform', tech: 'Python, Kubernetes, Docker, AWS' },
  { name: 'Comet ML', domain: 'comet.com', category: 'Machine Learning Platform', tech: 'Python, Java, Kubernetes, Docker' },
  { name: 'Voxel51', domain: 'voxel51.com', category: 'Computer Vision MLOps', tech: 'Python, React, Docker, Kubernetes' },
  { name: 'Clarifai', domain: 'clarifai.com', category: 'AI Visual & Audio', tech: 'Python, Go, Kubernetes, Triton, GPUs' },
  { name: 'Run:ai', domain: 'run.ai', category: 'AI Compute & Kubernetes', tech: 'Kubernetes, GPU Virtualization, Go' },
  { name: 'CoreWeave', domain: 'coreweave.com', category: 'AI Cloud Infrastructure', tech: 'Kubernetes, NVIDIA GPUs, Linux SRE' },
  { name: 'Lambda Labs', domain: 'lambdalabs.com', category: 'AI GPU Cloud', tech: 'Linux, Kubernetes, PyTorch, SRE' },
  { name: 'Together AI', domain: 'together.ai', category: 'Cloud for Open-Source AI', tech: 'Kubernetes, Rust, CUDA, Python' },
  { name: 'Anyscale', domain: 'anyscale.com', category: 'Ray & Distributed AI', tech: 'Ray, Python, Kubernetes, AWS, GCP' },
  { name: 'Modal', domain: 'modal.com', category: 'Serverless Cloud for AI', tech: 'Rust, Python, Linux Containers, GPUs' },
  { name: 'Baseten', domain: 'baseten.co', category: 'Machine Learning Inference', tech: 'Rust, Kubernetes, Python, AWS' },
  { name: 'Replicate', domain: 'replicate.com', category: 'Run AI with API', tech: 'Python, Go, Kubernetes, Docker' }
];

module.exports = { DEVOPS_COMPANIES };
